@startuml
	:Utilisateur: as client
    rectangle "Utilisateur déconnecté" as RecDeco {
        (Se connecter) as Connect
        (Visualiser une information) as Visu1
    }


	rectangle "Utilisateur connecté" as RecCo {
		rectangle "Consultation" as Consu{
		    (Init) as init
    	    (Visualiser une information) as Visu2
    	    (Lister toutes ses informations) as ListVisu
    	}
	    (Se déconnecter) as disconnect
	}

    note "Avec une clef publique" as publique

        client -> Connect
        client - publique
        publique -> Visu1
        Visu1 .. Visu2


    	Connect --> RecCo
    	disconnect -> RecDeco

    	init -> ListVisu

    	ListVisu -> Visu2
@enduml

Une information peut être trouver grâce à une clef public

L'utilisateur se connecte
L'utilisateur se déconnecte

L'utilisateur peut lister toutes ses informations
L'utilisateur peut regarder une information
L'utilisateur peut partager une information